[package]
name = "fcs_web"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "Document",
  "DomTokenList",
  "Element",
  "IntersectionObserver",
  "IntersectionObserverEntry",
  "IntersectionObserverInit",
  "NodeList",
  "Window"
] }
